apiVersion: v2
name: bare-metal-fulfillment-operator-crds
description: CRDs for the Bare Metal Fulfillment Operator
type: application
version: 0.0.11-nightly.20260923.f4461c3.37.1
appVersion: 0.0.11-nightly.20260923.f4461c3.37.1
